<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateMunicipalitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('municipalities', function (Blueprint $table) {
            $table->id();
            $table->string('name_municipality', 50);
            
            $table->unsignedBigInteger('state_id');
            
            $table->unsignedBigInteger('user_id');
            $table->timestamp('date_register')->nullable();
            $table->string('ip',20);

            $table->foreign('state_id')->references('id')->on('states');
            $table->foreign('user_id')->references('id')->on('users');
        });

        DB::table('municipalities')->insert([
          [
            'name_municipality' =>'Alto Orinoco',
            'state_id' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Atabapo',
            'state_id' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Atures',
            'state_id' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Autana',
            'state_id' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Manapiare',
            'state_id' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Maroa',
            'state_id' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Río Negro',
            'state_id' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Anaco',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Aragua',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Manuel Ezequiel Bruzual',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Diego Bautista Urbaneja',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Fernando Peñalver',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Francisco Del Carmen Carvajal',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'General Sir Arthur McGregor',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Guanta',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Independencia',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Gregorio Monagas',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Juan Antonio Sotillo',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Juan Manuel Cajigal',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertad',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Francisco de Miranda',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pedro María Freites',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Píritu',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San José de Guanipa',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Juan de Capistrano',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Santa Ana',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Simón Bolívar',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Simón Rodríguez',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Achaguas',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Biruaca',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Muñóz',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Páez',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pedro Camejo',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Rómulo Gallegos',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Fernando',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Atanasio Girardot',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bolívar',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Camatagua',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Francisco Linares Alcántara',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Ángel Lamas',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Félix Ribas',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Rafael Revenga',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertador',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Mario Briceño Iragorry',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Ocumare de la Costa de Oro',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Casimiro',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Sebastián',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Santiago Mariño',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Santos Michelena',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Tovar',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Urdaneta',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Zamora',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Alberto Arvelo Torrealba',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Andrés Eloy Blanco',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Antonio José de Sucre',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Arismendi',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Barinas',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bolívar',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cruz Paredes',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Ezequiel Zamora',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Obispos',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pedraza',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Rojas',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sosa',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Caroní',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cedeño',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'El Callao',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Gran Sabana',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Heres',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Piar',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Angostura (Raúl Leoni)',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Roscio',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sifontes',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Padre Pedro Chien',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bejuma',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Carlos Arvelo',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Diego Ibarra',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Guacara',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Juan José Mora',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertador',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Los Guayos',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Miranda',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Montalbán',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Naguanagua',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Puerto Cabello',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Diego',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Joaquín',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Valencia',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Anzoátegui',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Tinaquillo',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Girardot',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Lima Blanco',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pao de San Juan Bautista',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Ricaurte',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Rómulo Gallegos',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Carlos',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Tinaco',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Antonio Díaz',
            'state_id' =>'9',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Casacoima',
            'state_id' =>'9',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pedernales',
            'state_id' =>'9',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Tucupita',
            'state_id' =>'9',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Acosta',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bolívar',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Buchivacoa',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cacique Manaure',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Carirubana',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Colina',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Dabajuro',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Democracia',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Falcón',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Federación',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Jacura',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Laurencio Silva',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Los Taques',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Mauroa',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Miranda',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Monseñor Iturriza',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Palmasola',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Petit',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Píritu',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Francisco',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Tocópero',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Unión',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Urumaco',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Zamora',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Camaguán',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Chaguaramas',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'El Socorro',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Félix Ribas',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Tadeo Monagas',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Juan Germán Roscio',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Julián Mellado',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Las Mercedes',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Leonardo Infante',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pedro Zaraza',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Ortíz',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Gerónimo de Guayabal',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San José de Guaribe',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Santa María de Ipire',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sebastián Francisco de Miranda',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Andrés Eloy Blanco',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Crespo',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Iribarren',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Jiménez',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Morán',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Palavecino',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Simón Planas',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Torres',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Urdaneta',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Alberto Adriani',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Andrés Bello',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Antonio Pinto Salinas',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Aricagua',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Arzobispo Chacón',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Campo Elías',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Caracciolo Parra Olmedo',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cardenal Quintero',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Guaraque',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Julio César Salas',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Justo Briceño',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertador',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Miranda',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Obispo Ramos de Lora',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Padre Noguera',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pueblo Llano',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Rangel',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Rivas Dávila',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Santos Marquina',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Tovar',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Tulio Febres Cordero',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Zea',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Acevedo',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Andrés Bello',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Baruta',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Brión',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Buroz',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Carrizal',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Chacao',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cristóbal Rojas',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'El Hatillo',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Guaicaipuro',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Independencia',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Lander',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Los Salias',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Páez',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Paz Castillo',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pedro Gual',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Plaza',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Simón Bolívar',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Urdaneta',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Zamora',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Acosta',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Aguasay',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bolívar',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Caripe',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cedeño',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Ezequiel Zamora',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertador',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Maturín',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Piar',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Punceres',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Santa Bárbara',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sotillo',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Uracoa',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Antolín del Campo',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Arismendi',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'García',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Gómez',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Maneiro',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Marcano',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Mariño',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Península de Macanao',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Tubores',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Villalba',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Díaz',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Agua Blanca',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Araure',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Esteller',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Guanare',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Guanarito',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Monseñor José Vicente de Unda',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Ospino',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Páez',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Papelón',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Genaro de Boconoíto',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Rafael de Onoto',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Santa Rosalía',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Turén',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Andrés Eloy Blanco',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Andrés Mata',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Arismendi',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Benítez',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bermúdez',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bolívar',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cajigal',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cruz Salmerón Acosta',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertador',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Mariño',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Mejía',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Montes',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Ribero',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Valdéz',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Andrés Bello',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Antonio Rómulo Costa',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Ayacucho',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bolívar',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cárdenas',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Córdoba',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Fernández Feo',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Francisco de Miranda',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'García de Hevia',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Guásimos',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Independencia',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Jáuregui',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José María Vargas',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Junín',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertad',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertador',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Lobatera',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Michelena',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Panamericano',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pedro María Ureña',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Rafael Urdaneta',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Samuel Darío Maldonado',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Cristóbal',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Seboruco',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Simón Rodríguez',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Torbes',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Uribante',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Judas Tadeo',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Andrés Bello',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Boconó',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bolívar',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Candelaria',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Carache',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Escuque',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Felipe Márquez Cañizalez',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Juan Vicente Campos Elías',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'La Ceiba',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Miranda',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Monte Carmelo',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Motatán',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pampán',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Pampanito',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Rafael Rangel',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Rafael de Carvajal',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Trujillo',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Urdaneta',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Valera',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Vargas',
            'state_id' =>'21',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Arístides Bastidas',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bolívar',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Bruzual',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cocorote',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Independencia',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Antonio Páez',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'La Trinidad',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Manuel Monge',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Nirgua',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Peña',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Felipe',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Urachiche',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'José Joaquín Veroes',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Almirante Padilla',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Baralt',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Cabimas',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Catatumbo',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Colón',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Francisco Javier Pulgar',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Páez',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Jesús Enrique Losada',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Jesús María Semprún',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'La Cañada de Urdaneta',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Lagunillas',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Machiques de Perijá',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Mara',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Maracaibo',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Miranda',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Rosario de Perijá',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'San Francisco',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Santa Rita',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Simón Bolívar',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Sucre',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Valmore Rodríguez',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [         
            'name_municipality' =>'Libertador',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ]
        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('municipalities');
    }
}
