<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('code', 20);
            $table->string('name_country', 50);
            $table->string('abbreviation', 10);
            $table->string('code_phone', 20);
			      $table->boolean('default')->default(false);
        });
        DB::table('countries')->insert([
          [
          'name_country' =>'Venezuela',
          'abbreviation' =>'',
          'code_phone' => '+58',
          'code' => '0001',
		      'default' => 1,
          ],
          [
          'name_country' =>'Afghanistan ',
          'abbreviation' =>'',
          'code_phone' => '+93',
          'code' => '0002',
          'default' => 0,
          ],
          [
          'name_country' =>'Albania ',
          'abbreviation' =>'',
          'code_phone' => '+355',
          'code' => '0003',
          'default' => 0,
          ],
          [
          'name_country' =>'Algeria ',
          'abbreviation' =>'',
          'code_phone' => '+213',
          'code' => '0004',
          'default' => 0,
          ],
          [
          'name_country' =>'American Samoa',
          'abbreviation' =>'',
          'code_phone' => '+1-684',
          'code' => '0005',
          'default' => 0,
          ],
          [
          'name_country' =>'Andorra Principality of ',
          'abbreviation' =>'',
          'code_phone' => '+376',
          'code' => '0006',
          'default' => 0,
          ],
          [
          'name_country' =>'Angola',
          'abbreviation' =>'',
          'code_phone' => '+244',
          'code' => '0007',
          'default' => 0,
          ],
          [
          'name_country' =>'Anguilla ',
          'abbreviation' =>'',
          'code_phone' => '+1-264',
          'code' => '0008',
          'default' => 0,
          ],
          [
          'name_country' =>'Antarctica',
          'abbreviation' =>'',
          'code_phone' => '+672',
          'code' => '0009',
          'default' => 0,
          ],
          [
          'name_country' =>'Antigua and Barbuda',
          'abbreviation' =>'',
          'code_phone' => '+1-268',
          'code' => '0010',
          'default' => 0,
          ],
          [
          'name_country' =>'Argentina ',
          'abbreviation' =>'',
          'code_phone' => '+54',
          'code' => '0011',
          'default' => 0,
          ],
          [
          'name_country' =>'Armenia',
          'abbreviation' =>'',
          'code_phone' => '+374',
          'code' => '0012',
          'default' => 0,
          ],
          [
          'name_country' =>'Aruba',
          'abbreviation' =>'',
          'code_phone' => '+297',
          'code' => '0013',
          'default' => 0,
          ],
          [
          'name_country' =>'Australia',
          'abbreviation' =>'',
          'code_phone' => '+61',
          'code' => '0014',
          'default' => 0,
          ],
          [
          'name_country' =>'Austria',
          'abbreviation' =>'',
          'code_phone' => '+43',
          'code' => '0015',
          'default' => 0,
          ],
          [
          'name_country' =>'Azerbaijan',
          'abbreviation' =>'',
          'code_phone' => '+994',
          'code' => '0016',
          'default' => 0,
          ],
          [
          'name_country' =>'Bahamas Commonwealth of The',
          'abbreviation' =>'',
          'code_phone' => '+1-242',
          'code' => '0017',
          'default' => 0,
          ],
          [
          'name_country' =>'Bahrain Kingdom of ',
          'abbreviation' =>'',
          'code_phone' => '+973',
          'code' => '0018',
          'default' => 0,
          ],
          [
          'name_country' =>'Bangladesh',
          'abbreviation' =>'',
          'code_phone' => '+880',
          'code' => '0019',
          'default' => 0,
          ],
          [
          'name_country' =>'Barbados ',
          'abbreviation' =>'',
          'code_phone' => '+1-246',
          'code' => '0020',
          'default' => 0,
          ],
          [
          'name_country' =>'Belarus',
          'abbreviation' =>'',
          'code_phone' => '+375',
          'code' => '0021',
          'default' => 0,
          ],
          [
          'name_country' =>'Belgium ',
          'abbreviation' =>'',
          'code_phone' => '+32',
          'code' => '0022',
          'default' => 0,
          ],
          [
          'name_country' =>'Belize',
          'abbreviation' =>'',
          'code_phone' => '+501',
          'code' => '0023',
          'default' => 0,
          ],
          [
          'name_country' =>'Benin',
          'abbreviation' =>'',
          'code_phone' => '+229',
          'code' => '0024',
          'default' => 0,
          ],
          [
          'name_country' =>'Bermuda ',
          'abbreviation' =>'',
          'code_phone' => '+1-441',
          'code' => '0025',
          'default' => 0,
          ],
          [
          'name_country' =>'Bhutan Kingdom of',
          'abbreviation' =>'',
          'code_phone' => '+975',
          'code' => '0026',
          'default' => 0,
          ],
          [
          'name_country' =>'Bolivia ',
          'abbreviation' =>'',
          'code_phone' => '+591',
          'code' => '0027',
          'default' => 0,
          ],
          [
          'name_country' =>'Bosnia and Herzegovina ',
          'abbreviation' =>'',
          'code_phone' => '+387',
          'code' => '0028',
          'default' => 0,
          ],
          [
          'name_country' =>'Botswana',
          'abbreviation' =>'',
          'code_phone' => '+267',
          'code' => '0029',
          'default' => 0,
          ],
          [
          'name_country' =>'Brazil ',
          'abbreviation' =>'',
          'code_phone' => '+55',
          'code' => '0030',
          'default' => 0,
          ],
          [
          'name_country' =>'Brunei',
          'abbreviation' =>'',
          'code_phone' => '+673',
          'code' => '0031',
          'default' => 0,
          ],
          [
          'name_country' =>'Bulgaria ',
          'abbreviation' =>'',
          'code_phone' => '+359',
          'code' => '0032',
          'default' => 0,
          ],
          [
          'name_country' =>'Burkina Faso',
          'abbreviation' =>'',
          'code_phone' => '+226',
          'code' => '0033',
          'default' => 0,
          ],
          [
          'name_country' =>'Burundi',
          'abbreviation' =>'',
          'code_phone' => '+257',
          'code' => '0034',
          'default' => 0,
          ],
          [
          'name_country' =>'Cambodia Kingdom of',
          'abbreviation' =>'',
          'code_phone' => '+855',
          'code' => '0035',
          'default' => 0,
          ],
          [
          'name_country' =>'Cameroon',
          'abbreviation' =>'',
          'code_phone' => '+237',
          'code' => '0036',
          'default' => 0,
          ],
          [
          'name_country' =>'Canada ',
          'abbreviation' =>'',
          'code_phone' => '+1',
          'code' => '0037',
          'default' => 0,
          ],
          [
          'name_country' =>'Cape Verde ',
          'abbreviation' =>'',
          'code_phone' => '+238',
          'code' => '0038',
          'default' => 0,
          ],
          [
          'name_country' =>'Cayman Islands ',
          'abbreviation' =>'',
          'code_phone' => '+1-345',
          'code' => '0039',
          'default' => 0,
          ],
          [
          'name_country' =>'Central African Republic ',
          'abbreviation' =>'',
          'code_phone' => '+236',
          'code' => '0040',
          'default' => 0,
          ],
          [
          'name_country' =>'Chad ',
          'abbreviation' =>'',
          'code_phone' => '+235',
          'code' => '0041',
          'default' => 0,
          ],
          [
          'name_country' =>'Chile ',
          'abbreviation' =>'',
          'code_phone' => '+56',
          'code' => '0042',
          'default' => 0,
          ],
          [
          'name_country' =>'China ',
          'abbreviation' =>'',
          'code_phone' => '+86',
          'code' => '0043',
          'default' => 0,
          ],
          [
          'name_country' =>'Christmas Island ',
          'abbreviation' =>'',
          'code_phone' => '+53',
          'code' => '0044',
          'default' => 0,
          ],
          [
          'name_country' =>'Cocos Islands ',
          'abbreviation' =>'',
          'code_phone' => '+61',
          'code' => '0045',
          'default' => 0,
          ],
          [
          'name_country' =>'Colombia ',
          'abbreviation' =>'',
          'code_phone' => '+57',
          'code' => '0046',
          'default' => 0,
          ],
          [
          'name_country' =>'Comoros Union of the ',
          'abbreviation' =>'',
          'code_phone' => '+269',
          'code' => '0047',
          'default' => 0,
          ],
          [
          'name_country' =>'Congo Democratic Republic of the',
          'abbreviation' =>'',
          'code_phone' => '+243',
          'code' => '0048',
          'default' => 0,
          ],
          [
          'name_country' =>'Congo Republic of the',
          'abbreviation' =>'',
          'code_phone' => '+242',
          'code' => '0049',
          'default' => 0,
          ],
          [
          'name_country' =>'Cook Islands',
          'abbreviation' =>'',
          'code_phone' => '+682',
          'code' => '0050',
          'default' => 0,
          ],
          [
          'name_country' =>'Costa Rica ',
          'abbreviation' =>'',
          'code_phone' => '+506',
          'code' => '0051',
          'default' => 0,
          ],
          [
          'name_country' =>'Cote DIvoire',
          'abbreviation' =>'',
          'code_phone' => '+225',
          'code' => '0052',
          'default' => 0,
          ],
          [
          'name_country' =>'Croatia',
          'abbreviation' =>'',
          'code_phone' => '+385',
          'code' => '0053',
          'default' => 0,
          ],
          [
          'name_country' =>'Cuba ',
          'abbreviation' =>'',
          'code_phone' => '+53',
          'code' => '0054',
          'default' => 0,
          ],
          [
          'name_country' =>'Cyprus ',
          'abbreviation' =>'',
          'code_phone' => '+357',
          'code' => '0055',
          'default' => 0,
          ],
          [
          'name_country' =>'Czech Republic',
          'abbreviation' =>'',
          'code_phone' => '+420',
          'code' => '0056',
          'default' => 0,
          ],
          [
          'name_country' =>'Denmark ',
          'abbreviation' =>'',
          'code_phone' => '+45',
          'code' => '0057',
          'default' => 0,
          ],
          [
          'name_country' =>'Djibouti',
          'abbreviation' =>'',
          'code_phone' => '+253',
          'code' => '0058',
          'default' => 0,
          ],
          [
          'name_country' =>'Dominica ',
          'abbreviation' =>'',
          'code_phone' => '+1-767',
          'code' => '0059',
          'default' => 0,
          ],
          [
          'name_country' =>'Dominican Republic ',
          'abbreviation' =>'',
          'code_phone' => '+1-809',
          'code' => '0060',
          'default' => 0,
          ],
          [
          'name_country' =>'Dominican Republic ',
          'abbreviation' =>'',
          'code_phone' => '+1-829',
          'code' => '0061',
          'default' => 0,
          ],
          [
          'name_country' =>'East Timor',
          'abbreviation' =>'',
          'code_phone' => '+670',
          'code' => '0062',
          'default' => 0,
          ],
          [
          'name_country' =>'Ecuador ',
          'abbreviation' =>'',
          'code_phone' => '+593 ',
          'code' => '0063',
          'default' => 0,
          ],
          [
          'name_country' =>'Egypt',
          'abbreviation' =>'',
          'code_phone' => '+20',
          'code' => '0064',
          'default' => 0,
          ],
          [
          'name_country' =>'El Salvador ',
          'abbreviation' =>'',
          'code_phone' => '+503',
          'code' => '0065',
          'default' => 0,
          ],
          [
          'name_country' =>'Equatorial Guinea ',
          'abbreviation' =>'',
          'code_phone' => '+240',
          'code' => '0066',
          'default' => 0,
          ],
          [
          'name_country' =>'Eritrea ',
          'abbreviation' =>'',
          'code_phone' => '+291',
          'code' => '0067',
          'default' => 0,
          ],
          [
          'name_country' =>'Estonia ',
          'abbreviation' =>'',
          'code_phone' => '+372',
          'code' => '0068',
          'default' => 0,
          ],
          [
          'name_country' =>'Ethiopia ',
          'abbreviation' =>'',
          'code_phone' => '+251',
          'code' => '0069',
          'default' => 0,
          ],
          [
          'name_country' =>'Falkland Islands ',
          'abbreviation' =>'',
          'code_phone' => '+500',
          'code' => '0070',
          'default' => 0,
          ],
          [
          'name_country' =>'Faroe Islands ',
          'abbreviation' =>'',
          'code_phone' => '+298',
          'code' => '0071',
          'default' => 0,
          ],
          [
          'name_country' =>'Fiji ',
          'abbreviation' =>'',
          'code_phone' => '+679',
          'code' => '0072',
          'default' => 0,
          ],
          [
          'name_country' =>'Finland ',
          'abbreviation' =>'',
          'code_phone' => '+358',
          'code' => '0073',
          'default' => 0,
          ],
          [
          'name_country' =>'France ',
          'abbreviation' =>'',
          'code_phone' => '+33',
          'code' => '0074',
          'default' => 0,
          ],
          [
          'name_country' =>'French Guiana or French Guyana ',
          'abbreviation' =>'',
          'code_phone' => '+594',
          'code' => '0075',
          'default' => 0,
          ],
          [
          'name_country' =>'French Polynesia ',
          'abbreviation' =>'',
          'code_phone' => '+689',
          'code' => '0076',
          'default' => 0,
          ],
          [
          'name_country' =>'Gabon ',
          'abbreviation' =>'',
          'code_phone' => '+241',
          'code' => '0077',
          'default' => 0,
          ],
          [
          'name_country' =>'Gambia The ',
          'abbreviation' =>'',
          'code_phone' => '+220',
          'code' => '0078',
          'default' => 0,
          ],
          [
          'name_country' =>'Georgia ',
          'abbreviation' =>'',
          'code_phone' => '+995',
          'code' => '0079',
          'default' => 0,
          ],
          [
          'name_country' =>'Germany ',
          'abbreviation' =>'',
          'code_phone' => '+49',
          'code' => '0080',
          'default' => 0,
          ],
          [
          'name_country' =>'Ghana ',
          'abbreviation' =>'',
          'code_phone' => '+233',
          'code' => '0081',
          'default' => 0,
          ],
          [
          'name_country' =>'Gibraltar ',
          'abbreviation' =>'',
          'code_phone' => '+350',
          'code' => '0082',
          'default' => 0,
          ],
          [
          'name_country' =>'Greece ',
          'abbreviation' =>'',
          'code_phone' => '+30',
          'code' => '0083',
          'default' => 0,
          ],
          [
          'name_country' =>'Greenland ',
          'abbreviation' =>'',
          'code_phone' => '+299',
          'code' => '0084',
          'default' => 0,
          ],
          [
          'name_country' =>'Grenada ',
          'abbreviation' =>'',
          'code_phone' => '+1-473',
          'code' => '0085',
          'default' => 0,
          ],
          [
          'name_country' =>'Guadeloupe',
          'abbreviation' =>'',
          'code_phone' => '+590',
          'code' => '0086',
          'default' => 0,
          ],
          [
          'name_country' =>'Guam',
          'abbreviation' =>'',
          'code_phone' => '+1-671',
          'code' => '0087',
          'default' => 0,
          ],
          [
          'name_country' =>'Guatemala ',
          'abbreviation' =>'',
          'code_phone' => '+502',
          'code' => '0088',
          'default' => 0,
          ],
          [
          'name_country' =>'Guinea ',
          'abbreviation' =>'',
          'code_phone' => '+224',
          'code' => '0089',
          'default' => 0,
          ],
          [
          'name_country' =>'Guinea-Bissau ',
          'abbreviation' =>'',
          'code_phone' => '+245',
          'code' => '0090',
          'default' => 0,
          ],
          [
          'name_country' =>'Guyana ',
          'abbreviation' =>'',
          'code_phone' => '+592',
          'code' => '0091',
          'default' => 0,
          ],
          [
          'name_country' =>'Haiti ',
          'abbreviation' =>'',
          'code_phone' => '+509',
          'code' => '0092',
          'default' => 0,
          ],
          [
          'name_country' =>'Honduras ',
          'abbreviation' =>'',
          'code_phone' => '+504',
          'code' => '0093',
          'default' => 0,
          ],
          [
          'name_country' =>'Hong Kong ',
          'abbreviation' =>'',
          'code_phone' => '+852',
          'code' => '0094',
          'default' => 0,
          ],
          [
          'name_country' =>'Hungary ',
          'abbreviation' =>'',
          'code_phone' => '+36',
          'code' => '0095',
          'default' => 0,
          ],
          [
          'name_country' =>'Iceland ',
          'abbreviation' =>'',
          'code_phone' => '+354',
          'code' => '0096',
          'default' => 0,
          ],
          [
          'name_country' =>'India ',
          'abbreviation' =>'',
          'code_phone' => '+91',
          'code' => '0097',
          'default' => 0,
          ],
          [
          'name_country' =>'Indonesia ',
          'abbreviation' =>'',
          'code_phone' => '+62',
          'code' => '0098',
          'default' => 0,
          ],
          [
          'name_country' =>'Iran Islamic Republic of',
          'abbreviation' =>'',
          'code_phone' => '+98',
          'code' => '0099',
          'default' => 0,
          ],
          [
          'name_country' =>'Iraq ',
          'abbreviation' =>'',
          'code_phone' => '+964',
          'code' => '0100',
          'default' => 0,
          ],
          [
          'name_country' =>'Ireland ',
          'abbreviation' =>'',
          'code_phone' => '+353',
          'code' => '0101',
          'default' => 0,
          ],
          [
          'name_country' =>'Israel ',
          'abbreviation' =>'',
          'code_phone' => '+972',
          'code' => '0102',
          'default' => 0,
          ],
          [
          'name_country' =>'Italy ',
          'abbreviation' =>'',
          'code_phone' => '+39',
          'code' => '0103',
          'default' => 0,
          ],
          [
          'name_country' =>'Jamaica ',
          'abbreviation' =>'',
          'code_phone' => '+1-876',
          'code' => '0104',
          'default' => 0,
          ],
          [
          'name_country' =>'Japan ',
          'abbreviation' =>'',
          'code_phone' => '+81',
          'code' => '0105',
          'default' => 0,
          ],
          [
          'name_country' =>'Jordan ',
          'abbreviation' =>'',
          'code_phone' => '+962',
          'code' => '0106',
          'default' => 0,
          ],
          [
          'name_country' =>'Kazakstan',
          'abbreviation' =>'',
          'code_phone' => '+7',
          'code' => '0107',
          'default' => 0,
          ],
          [
          'name_country' =>'Kenya ',
          'abbreviation' =>'',
          'code_phone' => '+254',
          'code' => '0108',
          'default' => 0,
          ],
          [
          'name_country' =>'Kiribati ',
          'abbreviation' =>'',
          'code_phone' => '+686',
          'code' => '0109',
          'default' => 0,
          ],
          [
          'name_country' =>'Korea Democratic People Republic of ',
          'abbreviation' =>'',
          'code_phone' => '+850',
          'code' => '0110',
          'default' => 0,
          ],
          [
          'name_country' =>'Korea Republic of ',
          'abbreviation' =>'',
          'code_phone' => '+82',
          'code' => '0111',
          'default' => 0,
          ],
          [
          'name_country' =>'Kuwait ',
          'abbreviation' =>'',
          'code_phone' => '+965',
          'code' => '0112',
          'default' => 0,
          ],
          [
          'name_country' =>'Kyrgyzstan ',
          'abbreviation' =>'',
          'code_phone' => '+996',
          'code' => '0113',
          'default' => 0,
          ],
          [
          'name_country' =>'Lao People Democratic Republic ',
          'abbreviation' =>'',
          'code_phone' => '+856',
          'code' => '0114',
          'default' => 0,
          ],
          [
          'name_country' =>'Latvia ',
          'abbreviation' =>'',
          'code_phone' => '+371',
          'code' => '0115',
          'default' => 0,
          ],
          [
          'name_country' =>'Lebanon ',
          'abbreviation' =>'',
          'code_phone' => '+961',
          'code' => '0116',
          'default' => 0,
          ],
          [
          'name_country' =>'Lesotho ',
          'abbreviation' =>'',
          'code_phone' => '+266',
          'code' => '0117',
          'default' => 0,
          ],
          [
          'name_country' =>'Liberia ',
          'abbreviation' =>'',
          'code_phone' => '+231',
          'code' => '0118',
          'default' => 0,
          ],
          [
          'name_country' =>'Libya ',
          'abbreviation' =>'',
          'code_phone' => '+218',
          'code' => '0119',
          'default' => 0,
          ],
          [
          'name_country' =>'Liechtenstein ',
          'abbreviation' =>'',
          'code_phone' => '+423',
          'code' => '0120',
          'default' => 0,
          ],
          [
          'name_country' =>'Lithuania ',
          'abbreviation' =>'',
          'code_phone' => '+370',
          'code' => '0121',
          'default' => 0,
          ],
          [
          'name_country' =>'Luxembourg ',
          'abbreviation' =>'',
          'code_phone' => '+352',
          'code' => '0122',
          'default' => 0,
          ],
          [
          'name_country' =>'Macau ',
          'abbreviation' =>'',
          'code_phone' => '+853',
          'code' => '0123',
          'default' => 0,
          ],
          [
          'name_country' =>'Macedonia The Former Yugoslav Republic of',
          'abbreviation' =>'',
          'code_phone' => '+389',
          'code' => '0124',
          'default' => 0,
          ],
          [
          'name_country' =>'Madagascar ',
          'abbreviation' =>'',
          'code_phone' => '+261',
          'code' => '0125',
          'default' => 0,
          ],
          [
          'name_country' =>'Malawi ',
          'abbreviation' =>'',
          'code_phone' => '+265',
          'code' => '0126',
          'default' => 0,
          ],
          [
          'name_country' =>'Malaysia ',
          'abbreviation' =>'',
          'code_phone' => '+60',
          'code' => '0127',
          'default' => 0,
          ],
          [
          'name_country' =>'Maldives ',
          'abbreviation' =>'',
          'code_phone' => '+960',
          'code' => '0128',
          'default' => 0,
          ],
          [
          'name_country' =>'Mali ',
          'abbreviation' =>'',
          'code_phone' => '+223',
          'code' => '0129',
          'default' => 0,
          ],
          [
          'name_country' =>'Malta ',
          'abbreviation' =>'',
          'code_phone' => '+356',
          'code' => '0130',
          'default' => 0,
          ],
          [
          'name_country' =>'Marshall Islands ',
          'abbreviation' =>'',
          'code_phone' => '+692',
          'code' => '0131',
          'default' => 0,
          ],
          [
          'name_country' =>'Martinique ',
          'abbreviation' =>'',
          'code_phone' => '+596',
          'code' => '0132',
          'default' => 0,
          ],
          [
          'name_country' =>'Mauritania ',
          'abbreviation' =>'',
          'code_phone' => '+222',
          'code' => '0133',
          'default' => 0,
          ],
          [
          'name_country' =>'Mauritius ',
          'abbreviation' =>'',
          'code_phone' => '+230',
          'code' => '0134',
          'default' => 0,
          ],
          [
          'name_country' =>'Mayotte ',
          'abbreviation' =>'',
          'code_phone' => '+269',
          'code' => '0135',
          'default' => 0,
          ],
          [
          'name_country' =>'Mexico ',
          'abbreviation' =>'',
          'code_phone' => '+52',
          'code' => '0136',
          'default' => 0,
          ],
          [
          'name_country' =>'Micronesia Federated States of ',
          'abbreviation' =>'',
          'code_phone' => '+691',
          'code' => '0137',
          'default' => 0,
          ],
          [
          'name_country' =>'Moldova Republic of',
          'abbreviation' =>'',
          'code_phone' => '+373',
          'code' => '0138',
          'default' => 0,
          ],
          [
          'name_country' =>'Monaco Principality of',
          'abbreviation' =>'',
          'code_phone' => '+377',
          'code' => '0139',
          'default' => 0,
          ],
          [
          'name_country' =>'Mongolia ',
          'abbreviation' =>'',
          'code_phone' => '+976',
          'code' => '0140',
          'default' => 0,
          ],
          [
          'name_country' =>'Montserrat ',
          'abbreviation' =>'',
          'code_phone' => '+1-664',
          'code' => '0141',
          'default' => 0,
          ],
          [
          'name_country' =>'Morocco ',
          'abbreviation' =>'',
          'code_phone' => '+212',
          'code' => '0142',
          'default' => 0,
          ],
          [
          'name_country' =>'Mozambique ',
          'abbreviation' =>'',
          'code_phone' => '+258',
          'code' => '0143',
          'default' => 0,
          ],
          [
          'name_country' =>'Myanmar Union of ',
          'abbreviation' =>'',
          'code_phone' => '+95',
          'code' => '0144',
          'default' => 0,
          ],
          [
          'name_country' =>'Namibia ',
          'abbreviation' =>'',
          'code_phone' => '+264',
          'code' => '0145',
          'default' => 0,
          ],
          [
          'name_country' =>'Nauru ',
          'abbreviation' =>'',
          'code_phone' => '+674',
          'code' => '0146',
          'default' => 0,
          ],
          [
          'name_country' =>'Nepal ',
          'abbreviation' =>'',
          'code_phone' => '+977',
          'code' => '0147',
          'default' => 0,
          ],
          [
          'name_country' =>'Netherlands ',
          'abbreviation' =>'',
          'code_phone' => '+31',
          'code' => '0148',
          'default' => 0,
          ],
          [
          'name_country' =>'Netherlands Antilles ',
          'abbreviation' =>'',
          'code_phone' => '+599',
          'code' => '0149',
          'default' => 0,
          ],
          [
          'name_country' =>'New Caledonia ',
          'abbreviation' =>'',
          'code_phone' => '+687',
          'code' => '0150',
          'default' => 0,
          ],
          [
          'name_country' =>'New Zealand ',
          'abbreviation' =>'',
          'code_phone' => '+64',
          'code' => '0151',
          'default' => 0,
          ],
          [
          'name_country' =>'Nicaragua ',
          'abbreviation' =>'',
          'code_phone' => '+505',
          'code' => '0152',
          'default' => 0,
          ],
          [
          'name_country' =>'Niger ',
          'abbreviation' =>'',
          'code_phone' => '+227',
          'code' => '0153',
          'default' => 0,
          ],
          [
          'name_country' =>'Nigeria ',
          'abbreviation' =>'',
          'code_phone' => '+234',
          'code' => '0154',
          'default' => 0,
          ],
          [
          'name_country' =>'Niue ',
          'abbreviation' =>'',
          'code_phone' => '+683',
          'code' => '0155',
          'default' => 0,
          ],
          [
          'name_country' =>'Norfolk Island ',
          'abbreviation' =>'',
          'code_phone' => '+672',
          'code' => '0156',
          'default' => 0,
          ],
          [
          'name_country' =>'Northern Mariana Islands ',
          'abbreviation' =>'',
          'code_phone' => '+1-670',
          'code' => '0157',
          'default' => 0,
          ],
          [
          'name_country' =>'Norway ',
          'abbreviation' =>'',
          'code_phone' => '+47',
          'code' => '0158',
          'default' => 0,
          ],
          [
          'name_country' =>'Oman Sultanate of ',
          'abbreviation' =>'',
          'code_phone' => '+968',
          'code' => '0159',
          'default' => 0,
          ],
          [
          'name_country' =>'Pakistan ',
          'abbreviation' =>'',
          'code_phone' => '+92',
          'code' => '0160',
          'default' => 0,
          ],
          [
          'name_country' =>'Palau ',
          'abbreviation' =>'',
          'code_phone' => '+680',
          'code' => '0161',
          'default' => 0,
          ],
          [
          'name_country' =>'Palestinian State ',
          'abbreviation' =>'',
          'code_phone' => '+970',
          'code' => '0162',
          'default' => 0,
          ],
          [
          'name_country' =>'Panama ',
          'abbreviation' =>'',
          'code_phone' => '+507',
          'code' => '0163',
          'default' => 0,
          ],
          [
          'name_country' =>'Papua New Guinea ',
          'abbreviation' =>'',
          'code_phone' => '+675',
          'code' => '0164',
          'default' => 0,
          ],
          [
          'name_country' =>'Paraguay ',
          'abbreviation' =>'',
          'code_phone' => '+595',
          'code' => '0165',
          'default' => 0,
          ],
          [
          'name_country' =>'Peru ',
          'abbreviation' =>'',
          'code_phone' => '+51',
          'code' => '0166',
          'default' => 0,
          ],
          [
          'name_country' =>'Philippines ',
          'abbreviation' =>'',
          'code_phone' => '+63',
          'code' => '0167',
          'default' => 0,
          ],
          [
          'name_country' =>'Poland ',
          'abbreviation' =>'',
          'code_phone' => '+48',
          'code' => '0168',
          'default' => 0,
          ],
          [
          'name_country' =>'Portugal ',
          'abbreviation' =>'',
          'code_phone' => '+351',
          'code' => '0169',
          'default' => 0,
          ],
          [
          'name_country' =>'Puerto Rico ',
          'abbreviation' =>'',
          'code_phone' => '+1-787',
          'code' => '0170',
          'default' => 0,
          ],
          [
          'name_country' =>'Puerto Rico ',
          'abbreviation' =>'',
          'code_phone' => '+1-939',
          'code' => '0171',
          'default' => 0,
          ],
          [
          'name_country' =>'Qatar State of ',
          'abbreviation' =>'',
          'code_phone' => '+974 ',
          'code' => '0172',
          'default' => 0,
          ],
          [
          'name_country' =>'Reunion ',
          'abbreviation' =>'',
          'code_phone' => '+262',
          'code' => '0173',
          'default' => 0,
          ],
          [
          'name_country' =>'Romania ',
          'abbreviation' =>'',
          'code_phone' => '+40',
          'code' => '0174',
          'default' => 0,
          ],
          [
          'name_country' =>'Russian Federation ',
          'abbreviation' =>'',
          'code_phone' => '+7',
          'code' => '0175',
          'default' => 0,
          ],
          [
          'name_country' =>'Rwanda ',
          'abbreviation' =>'',
          'code_phone' => '+250',
          'code' => '0176',
          'default' => 0,
          ],
          [
          'name_country' =>'Saint Helena ',
          'abbreviation' =>'',
          'code_phone' => '+290',
          'code' => '0177',
          'default' => 0,
          ],
          [
          'name_country' =>'Saint Kitts and Nevis ',
          'abbreviation' =>'',
          'code_phone' => '+1-869',
          'code' => '0178',
          'default' => 0,
          ],
          [
          'name_country' =>'Saint Lucia ',
          'abbreviation' =>'',
          'code_phone' => '+1-758',
          'code' => '0179',
          'default' => 0,
          ],
          [
          'name_country' =>'Saint Pierre and Miquelon ',
          'abbreviation' =>'',
          'code_phone' => '+508',
          'code' => '0180',
          'default' => 0,
          ],
          [
          'name_country' =>'Saint Vincent and the Grenadines ',
          'abbreviation' =>'',
          'code_phone' => '+1-784',
          'code' => '0181',
          'default' => 0,
          ],
          [
          'name_country' =>'Samoa ',
          'abbreviation' =>'',
          'code_phone' => '+685',
          'code' => '0182',
          'default' => 0,
          ],
          [
          'name_country' =>'San Marino ',
          'abbreviation' =>'',
          'code_phone' => '+378',
          'code' => '0183',
          'default' => 0,
          ],
          [
          'name_country' =>'Sao Tome and Principe ',
          'abbreviation' =>'',
          'code_phone' => '+239',
          'code' => '0184',
          'default' => 0,
          ],
          [
          'name_country' =>'Saudi Arabia ',
          'abbreviation' =>'',
          'code_phone' => '+966',
          'code' => '0185',
          'default' => 0,
          ],
          [
          'name_country' =>'Senegal ',
          'abbreviation' =>'',
          'code_phone' => '+221',
          'code' => '0186',
          'default' => 0,
          ],
          [
          'name_country' =>'Seychelles ',
          'abbreviation' =>'',
          'code_phone' => '+248',
          'code' => '0187',
          'default' => 0,
          ],
          [
          'name_country' =>'Sierra Leone ',
          'abbreviation' =>'',
          'code_phone' => '+232',
          'code' => '0188',
          'default' => 0,
          ],
          [
          'name_country' =>'Singapore ',
          'abbreviation' =>'',
          'code_phone' => '+65',
          'code' => '0189',
          'default' => 0,
          ],
          [
          'name_country' =>'Slovakia',
          'abbreviation' =>'',
          'code_phone' => '+421',
          'code' => '0190',
          'default' => 0,
          ],
          [
          'name_country' =>'Slovenia ',
          'abbreviation' =>'',
          'code_phone' => '+386',
          'code' => '0191',
          'default' => 0,
          ],
          [
          'name_country' =>'Solomon Islands ',
          'abbreviation' =>'',
          'code_phone' => '+677',
          'code' => '0192',
          'default' => 0,
          ],
          [
          'name_country' =>'Somalia ',
          'abbreviation' =>'',
          'code_phone' => '+252',
          'code' => '0193',
          'default' => 0,
          ],
          [
          'name_country' =>'South Africa ',
          'abbreviation' =>'',
          'code_phone' => '+27',
          'code' => '0194',
          'default' => 0,
          ],
          [
          'name_country' =>'Spain ',
          'abbreviation' =>'',
          'code_phone' => '+34',
          'code' => '0195',
          'default' => 0,
          ],
          [
          'name_country' =>'Sri Lanka ',
          'abbreviation' =>'',
          'code_phone' => '+94',
          'code' => '0196',
          'default' => 0,
          ],
          [
          'name_country' =>'Sudan ',
          'abbreviation' =>'',
          'code_phone' => '+249',
          'code' => '0197',
          'default' => 0,
          ],
          [
          'name_country' =>'Suriname ',
          'abbreviation' =>'',
          'code_phone' => '+597',
          'code' => '0198',
          'default' => 0,
          ],
          [
          'name_country' =>'Swaziland Kingdom of ',
          'abbreviation' =>'',
          'code_phone' => '+268',
          'code' => '0199',
          'default' => 0,
          ],
          [
          'name_country' =>'Sweden ',
          'abbreviation' =>'',
          'code_phone' => '+46',
          'code' => '0200',
          'default' => 0,
          ],
          [
          'name_country' =>'Switzerland ',
          'abbreviation' =>'',
          'code_phone' => '+41',
          'code' => '0201',
          'default' => 0,
          ],
          [
          'name_country' =>'Syria ',
          'abbreviation' =>'',
          'code_phone' => '+963',
          'code' => '0202',
          'default' => 0,
          ],
          [
          'name_country' =>'Taiwan ',
          'abbreviation' =>'',
          'code_phone' => '+886',
          'code' => '0203',
          'default' => 0,
          ],
          [
          'name_country' =>'Tajikistan ',
          'abbreviation' =>'',
          'code_phone' => '+992',
          'code' => '0204',
          'default' => 0,
          ],
          [
          'name_country' =>'Tanzania United Republic of ',
          'abbreviation' =>'',
          'code_phone' => '+255',
          'code' => '0205',
          'default' => 0,
          ],
          [
          'name_country' =>'Thailand ',
          'abbreviation' =>'',
          'code_phone' => '+66',
          'code' => '0206',
          'default' => 0,
          ],
          [
          'name_country' =>'Tokelau ',
          'abbreviation' =>'',
          'code_phone' => '+690',
          'code' => '0207',
          'default' => 0,
          ],
          [
          'name_country' =>'Tonga Kingdom of ',
          'abbreviation' =>'',
          'code_phone' => '+676',
          'code' => '0208',
          'default' => 0,
          ],
          [
          'name_country' =>'Trinidad and Tobago ',
          'abbreviation' =>'',
          'code_phone' => '+1-868',
          'code' => '0209',
          'default' => 0,
          ],
          [
          'name_country' =>'Tunisia ',
          'abbreviation' =>'',
          'code_phone' => '+216',
          'code' => '0210',
          'default' => 0,
          ],
          [
          'name_country' =>'Turkey ',
          'abbreviation' =>'',
          'code_phone' => '+90',
          'code' => '0211',
          'default' => 0,
          ],
          [
          'name_country' =>'Turkmenistan ',
          'abbreviation' =>'',
          'code_phone' => '+993',
          'code' => '0212',
          'default' => 0,
          ],
          [
          'name_country' =>'Turks and Caicos Islands ',
          'abbreviation' =>'',
          'code_phone' => '+1-649',
          'code' => '0213',
          'default' => 0,
          ],
          [
          'name_country' =>'Tuvalu ',
          'abbreviation' =>'',
          'code_phone' => '+688',
          'code' => '0214',
          'default' => 0,
          ],
          [
          'name_country' =>'Uganda Republic of',
          'abbreviation' =>'',
          'code_phone' => '+256',
          'code' => '0215',
          'default' => 0,
          ],
          [
          'name_country' =>'Ukraine ',
          'abbreviation' =>'',
          'code_phone' => '+380',
          'code' => '0216',
          'default' => 0,
          ],
          [
          'name_country' =>'United Arab Emirates ',
          'abbreviation' =>'',
          'code_phone' => '+971',
          'code' => '0217',
          'default' => 0,
          ],
          [
          'name_country' =>'United Kingdom ',
          'abbreviation' =>'',
          'code_phone' => '+44',
          'code' => '0218',
          'default' => 0,
          ],
          [
          'name_country' =>'United States ',
          'abbreviation' =>'',
          'code_phone' => '+1',
          'code' => '0219',
          'default' => 0,
          ],
          [
          'name_country' =>'Uruguay Oriental Republic of ',
          'abbreviation' =>'',
          'code_phone' => '+598',
          'code' => '0220',
          'default' => 0,
          ],
          [
          'name_country' =>'Uzbekistan ',
          'abbreviation' =>'',
          'code_phone' => '+998',
          'code' => '0221',
          'default' => 0,
          ],
          [
          'name_country' =>'Vanuatu ',
          'abbreviation' =>'',
          'code_phone' => '+678',
          'code' => '0222',
          'default' => 0,
          ],
          [
          'name_country' =>'Vatican City State ',
          'abbreviation' =>'',
          'code_phone' => '+418',
          'code' => '0223',
          'default' => 0,
          ],
          [
          'name_country' =>'Vietnam ',
          'abbreviation' =>'',
          'code_phone' => '+84',
          'code' => '0224',
          'default' => 0,
          ],
          [
          'name_country' =>'Virgin Islands British ',
          'abbreviation' =>'',
          'code_phone' => '+1-284',
          'code' => '0225',
          'default' => 0,
          ],
          [
          'name_country' =>'Virgin Islands United States ',
          'abbreviation' =>'',
          'code_phone' => '+1-340',
          'code' => '0226',
          'default' => 0,
          ],
          [
          'name_country' =>'Wallis and Futuna Islands ',
          'abbreviation' =>'',
          'code_phone' => '+681',
          'code' => '0227',
          'default' => 0,
          ],
          [
          'name_country' =>'Yemen ',
          'abbreviation' =>'',
          'code_phone' => '+967',
          'code' => '0228',
          'default' => 0,
          ],
          [
          'name_country' =>'Zambia Republic of ',
          'abbreviation' =>'',
          'code_phone' => '+260',
          'code' => '0229',
          'default' => 0,
          ],
          [
          'name_country' =>'Zimbabwe Republic of ',
          'abbreviation' =>'',
          'code_phone' => '+263',
          'code' => '0230',
          'default' => 0,
          ]

        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
