<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePostalCodesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('postal_codes', function (Blueprint $table) {
            $table->id();
            $table->string('code', 8);
            
            $table->unsignedBigInteger('state_id');            
            $table->unsignedBigInteger('user_id');
            $table->timestamp('date_register')->nullable();
            $table->string('ip',20);

            $table->foreign('state_id')->references('id')->on('states');
            $table->foreign('user_id')->references('id')->on('users');
        });
        
        DB::table('postal_codes')->insert([  
          [     
            'code' =>'6001',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6002',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6003',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6007',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6008',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6009',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6012',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6014',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6016',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6020',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6022',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6023',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6027',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6032',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6048',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6050',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6052',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6054',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6055',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6057',
            'state_id' =>'2',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5063',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5067',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7001',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7002',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7003',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7004',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7005',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7007',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7010',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7011',
            'state_id' =>'3',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2101',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2102',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2103',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2104',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2105',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2107',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2110',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2112',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2113',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2114',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2115',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2116',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2117',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2118',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2119',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2121',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2122',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2123',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2125',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2126',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2127',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2128',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2311',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2334',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2335',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2338',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2340',
            'state_id' =>'4',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5201',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5203',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5206',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5207',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5208',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5210',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5213',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5214',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5216',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5217',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5219',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5220',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5221',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5224',
            'state_id' =>'5',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8001',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8003',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8009',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8011',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8013',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8050',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8051',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8052',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8054',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8055',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8056',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8057',
            'state_id' =>'6',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2001',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2002',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2003',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2005',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2006',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2010',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2015',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2016',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2017',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2018',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2035',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2039',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2040',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2041',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2042',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2044',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2050',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2051',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2053',
            'state_id' =>'7',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2201',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2203',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2204',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2206',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2207',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2209',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2213',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2214',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2216',
            'state_id' =>'8',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2052',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2054',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2055',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4101',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4102',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4103',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4104',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4109',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4110',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4114',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4117',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4118',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4132',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4136',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4137',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4150',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4152',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4154',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4167',
            'state_id' =>'10',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2301',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2303',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2304',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2305',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2312',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2316',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2319',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2320',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2332',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2350',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2351',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2354',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2355',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2356',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2358',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'8007',
            'state_id' =>'11',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3001',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3004',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3009',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3015',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3016',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3021',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3023',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3025',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3028',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3031',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3032',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3033',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3034',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3050',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3051',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3052',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3054',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3055',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3056',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3057',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3058',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3059',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3060',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3061',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3063',
            'state_id' =>'12',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3112',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3133',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5101',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5102',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5105',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5106',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5107',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5108',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5110',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5111',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5112',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5114',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5115',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5116',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5124',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5129',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5130',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5131',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5133',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5134',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5138',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5141',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5142',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5144',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5145',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5154',
            'state_id' =>'13',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1070',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1073',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1080',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1201',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1203',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1204',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1209',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1210',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1211',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1212',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1214',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1215',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1220',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1221',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1224',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1225',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1226',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1228',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1231',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1232',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1235',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1238',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1241',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1243',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1245',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1246',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2120',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6005',
            'state_id' =>'14',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6201',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6202',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6204',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6206',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6207',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6208',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6209',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6210',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6211',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6213',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6214',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6215',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6216',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6218',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6219',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6221',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6223',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6224',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6225',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6226',
            'state_id' =>'15',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6301',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6304',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6309',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6311',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6316',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6320',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6321',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6322',
            'state_id' =>'16',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3301',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3302',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3303',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3304',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3305',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3306',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3307',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3309',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3317',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3350',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3351',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3352',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3353',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3354',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3355',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3357',
            'state_id' =>'17',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'2302',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6101',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6102',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6106',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6107',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6110',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6123',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6126',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6150',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6152',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6154',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6155',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6156',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6160',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6161',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6163',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6164',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6167',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6168',
            'state_id' =>'18',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5001',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5002',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5003',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5009',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5010',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5012',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5015',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5017',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5020',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5021',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5022',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5027',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5032',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5033',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5036',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5037',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5038',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5048',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5051',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5054',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5058',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5062',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5065',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5143',
            'state_id' =>'19',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3101',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3102',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3103',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3104',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3105',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3106',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3107',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3108',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3109',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3110',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3113',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3115',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3116',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3118',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3119',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3122',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3123',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3124',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3125',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3127',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3128',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3129',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3132',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3134',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3135',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3136',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3140',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3145',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3146',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3147',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3149',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3150',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3151',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3152',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3153',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3154',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3156',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3157',
            'state_id' =>'20',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1160',
            'state_id' =>'21',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1162',
            'state_id' =>'21',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1165',
            'state_id' =>'21',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1166',
            'state_id' =>'21',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1168',
            'state_id' =>'21',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3201',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3202',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3203',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3205',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3206',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3207',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3209',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3210',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3211',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3214',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3222',
            'state_id' =>'22',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3137',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3141',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3158',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'3164',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4001',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4002',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4004',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4005',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4011',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4012',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4013',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4014',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4015',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4016',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4017',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4019',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4020',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4021',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4022',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4032',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4033',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4036',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4037',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4043',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4044',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4045',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4046',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'4047',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5147',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'5148',
            'state_id' =>'23',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1000',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1010',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1011',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1020',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1030',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1040',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1041',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1050',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1052',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1053',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1060',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1061',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1062',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1064',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1071',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1081',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1083',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1086',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1090',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1223',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'1262',
            'state_id' =>'24',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'6401',
            'state_id' =>'9',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [            
            'code' =>'7101',
            'state_id' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('postal_codes');
    }
}
