<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateEconomicSectorsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('economic_sectors', function (Blueprint $table) {
            $table->id();
            $table->string('name_economic_sector', 50);
            $table->boolean('status')->default(true);
            
            $table->unsignedBigInteger('user_id');
            $table->timestamp('date_register')->nullable();
            $table->string('ip',20);

            $table->foreign('user_id')->references('id')->on('users');
        });

        DB::table('economic_sectors')->insert([
          [
            'name_economic_sector' =>'CIA PANAMENA DE AVIACION',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERVICIOS VETERINARIOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'AGRICULTURA COOPERATIVAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERVIC DE HORTIC Y JARDIN',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONTR GENER RESID Y COMER',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONTR A C CALEF Y PLOMER',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONTRATISTAS DE ELECTRIC',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONTR DE ALBAN ENYES MAMP',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONTRATISTA CARPINTERIA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONTR TECHO REVESTIMIENTO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONTRAT TRAB EN CONCRETO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONTRAT OFICIO ESPECIAL',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EDITOR E IMPRENT MISCELAN',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PLANTIL TIPOGR SERV RELAC',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PREPARAC LIMPIEZA ESPEC',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'FERROCARRIL FLETE',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TRANS PASAJ BARCOS TRANSB',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'FERROCARRILES PASAJEROS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV DE AMBULANCIAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'LIMOSINAS TAXIS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ALQUILER BUS TURISMO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'COMP MUDANZA CARGA PESADA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV MENSAJE AEREO Y TERR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ALMAC AGRICOL ARTIC HOGAR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV CORREO CURRIER',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'LINEAS DE CRUCEROS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ALQUILER BOTE RENTA BOTE',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV MARINOS SUMINIS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'AEROLINEA NO CLASIFICADOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TERMINALES DE AEROPUERTOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'AGENC VIAJES TURISMO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PACKGE TOUR OPERATORS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MAYORISTAS DE VIAJES',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PEAJES',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERVIC TRANSPORT NO CLASF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EQP TELECOM VTA TELF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CTRO TELCOM CON BANDA MAG',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV TLF V Y M PHONE',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV INF REDES COMP TELF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV TELEGRAFICOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TRANSFER DINERO COMERCIO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV CABLE TV RADIO SATEL',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SERV PBLCOS GAS AGUA ASEO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'REPUEST VEHICULOS TELFV',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MBLES OFC COMERC TELF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MATERIAL CONSTRUCC TELF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EQP FTOGRAF FOTOCOP MICRO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EQ COMP SOFTW HARDW TLF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EQ COMERCIAL NO CLASIFIC',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EQP Y MATER MEDICOS GENER',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CTROS Y OFIC SERVC METAL',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PARTES EQPOS ELECTR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EQP Y MATER DE FERRETERIA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EQ CALEFACC PLOMERIA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MATER INDUST NO CLASIFIC',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PIEDRAS PRECIOSAS Y METAL',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MERC NO PERCEDERA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SUMIN OFC PAPELERIA TELF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MEDICINAS PROP MED PATENT',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ART COSTURA ART TEXTILES',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDAS DE UNIFORMES TELF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CALZADO COMERCIAL',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'QUIMICOS PROD DERIV PROD',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PETROLEO Y DERIVADOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'LIBROS Y PERIODICOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VIVEROS SUMIN FLORES',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PINTURAS BARNIS SUM',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MERCANCIA PERECEDERA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'HYPERTIENDAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA MATERIAL CONST MADER',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA VIDRI PINT PPEL TAPIZ',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'FERRETERIAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VIVEROS EQPOS JARDINERIA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTAS CASAS REMOLQUESS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CLUB DE ALMACENES',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TIENDA LIBRE DE IMPUESTOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA DESCUENTO FB DET',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDAS P DEPARTAMENTOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDAS VARIEDADES BAZAR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'LIMOSINAS TAXIS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDAS MERCANCIA GRAL',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SUPERMERCADOS ABASTOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PROVE CONGEL REFRIG CARNE',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'DULCERIAS BOMBONERIAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA PRODUC LACTEOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PANADERIA PASTELERIA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA DELICATES ROSTISSERIA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONC AUTO CAMI SERV REPAR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CONCENS VEHIC USADOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDAS DE AUTOS MATER HOGAR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTAS CAUCHOS DE VEHICULOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTAS RPTOS ACC VEHICULOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ESTAC DE SERVICIOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'DISPENS AUTOM GASOLINA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTAS DE LANCHAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VENDEDORES DE CAMPERS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTAS MOTOCICLETAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTA CASA MOVIL MOTORIZADA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VENDEDORES DE MOTONIEVES',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTAS VEHIC NO CLASIFICAD',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ROPA MASC JOV Y ADULTOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ROPA FEMENINA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ACCESOR ART FEMENINOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ROPA DE BEBES Y NINOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA ROPA TODA FAMILIA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA ROPA DEPORT EQUITAC',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ZAPATERIAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PELETERIAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ROPA UNISEX',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'SASTRE MODIST ARREGLOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PELUCAS Y POSTIZOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA DE ACCESORIOS Y ROPA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA MUEBLES PARA EL HOGAR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TIENDAS DE PISOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CORTINAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CHIMENEAS ACCESORIOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA MISC ESPC MOBIL HOGAR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDAS DE ELECTRODOMESTICOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTAS DE EQP ELECTRONICOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA MUSICA INSTRUM PIANOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA COMPUTADORAS SOFTWARE',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TIENDA DE DISCOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PROVEE COMIDA POR ENCARGO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'RESTAURANT BAR',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'EXPEND LIC BARES TASCAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'COMIDAS RAPIDAS FTE SODAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'LIBROS PELICULAS MUSICA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'JUEGOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'APLICACIONES EXCL JUEGOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PROD DIG GRANDE COMERCIOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'FARMACIAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'LICORERIAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTA MERC USADA 2DA MANO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA DE ANTIGUEDADES',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CASAS DE EMPENOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CHIVERAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ANTIGUEDAD REPRODUCCIONES',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTA SERV BICICLETAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA ARTIC DEPORTIVOS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'LIBRERIAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'PAPEL UTIL ESC OFC',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'RELOJES JOYERIAS VAJILLAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TIENDAS DE JUEGOS HOBBY',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA CAMARA ART FOTOGRAF',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA RGLOS TARJET NOVED',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ARTICULOS DE CUEROS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDAS TELAS MATER COSTURA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDAS CRISTAL ARTIC VIDRIO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MERCAD DIRECT SEGURO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'MERCADEO DIRECTO VIAJE',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTA DIREC POR PUERTA',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VENTAS POR CATALOGO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'CATALG VTA POR MENO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TELEMERC P CORREO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTA POR TELEFONO',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'VTA SUSCRIPC CONTIN',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'OTROS MERCADEO DIREC',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'ART ARTES PLASTICAS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'GALERIAS ARTE COMERCIANTE',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ],
          [        
            'name_economic_sector' =>'TDA ESTAMPILL NUMISMS',
            'status' =>'1',
            'user_id' => '1',
            'date_register' => now(),
            'ip' => \Request::ip(),
          ]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('economic_sectors');
    }
}
